{{- if not .Values.existingConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: {{- toYaml .Values.config | nindent 2 }}
  {{- if and .Values.authentication.passwordEntries .Values.authentication.passwordFilePath }}
    password_file {{ .Values.authentication.passwordFilePath }}
  {{- end }}
  {{- if and .Values.authorization.acls .Values.authorization.aclfilePath }}
    acl_file {{ .Values.authorization.aclfilePath }}
  {{- end }}
{{- end }}
