apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels: {{- include "mosquitto.selector" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "mosquitto.selector" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
      {{- if and .Values.authentication.passwordEntries .Values.authentication.passwordFilePath }}
        checksum/secret: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum | trunc 63 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | indent 8 | trim }}
    {{- end }}
      serviceAccountName: {{ include "mosquitto.serviceAccountName" . }}
    {{- with .Values.podSecurityContext }}
      securityContext:
        {{ toYaml . | indent 8 | trim }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.ports }}
          ports:
          {{- range $key, $value := . }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: {{ default "TCP" $value.protocol }}
          {{- end }}
        {{- end }}
          livenessProbe:
            tcpSocket:
              port: websocket
            initialDelaySeconds: 5
            periodSeconds: 1
          readinessProbe:
            tcpSocket:
              port: websocket
            initialDelaySeconds: 3
            periodSeconds: 3
        {{- with .Values.securityContext }}
          securityContext:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
        {{- with .Values.resources }}
          resources:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
              subPath: {{ .Values.persistence.subPath }}
          {{- if and .Values.authentication.passwordEntries .Values.authentication.passwordFilePath }}
            - name: passwordfile
              mountPath: {{ .Values.authentication.passwordFilePath }}
              subPath: passwordfile
          {{- end }}
          {{- if and .Values.authorization.acls .Values.authorization.aclfilePath }}
            - name: aclfile
              mountPath: {{ .Values.authorization.aclfilePath }}
              subPath: aclfile
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{ toYaml . | indent 12 | trim }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ if .Values.existingConfigMap }}{{ .Values.existingConfigMap }}{{ else }}{{ include "mosquitto.fullname" . }}{{ end }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "mosquitto.fullname" . }}{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if and .Values.authentication.passwordEntries .Values.authentication.passwordFilePath }}
        - name: passwordfile
          secret:
            secretName: {{ include "mosquitto.fullname" . }}
      {{- end }}
      {{- if and .Values.authorization.acls .Values.authorization.aclfilePath }}
        - name: aclfile
          secret:
            secretName: {{ include "mosquitto.fullname" . }}
      {{- end }}
      {{- with .Values.extraVolumes }}
        {{ toYaml . | indent 8 | trim }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 | trim }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 | trim }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 | trim }}
    {{- end }}
