apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- with .Values.ports }}
  ports:
  {{- range $key, $value := . }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $key }}
      protocol: {{ default "TCP" $value.protocol }}
  {{- end }}
{{- end }}
  selector: {{- include "mosquitto.selector" . | nindent 4 }}
